import type { FilterId } from './filters.ts';
import { regionalLandmarks } from './landmarks.ts';
import { terrainHeight } from './terrain.ts';
export type Category = 'Nature' | 'Sports' | 'News' | 'Wedding' | 'Studio' | 'Astro';
export type Technique = 'landscape' | 'water' | 'freeze' | 'pan' | 'glass' | 'news' | 'couple' | 'group' | 'portrait' | 'environmental' | 'product' | 'stars' | 'trails' | 'bird' | 'wildlife' | 'meeting' | 'bear';
export interface MissionShot {
  id: string; title: string; description: string;
  /** Horizontal camera distance and bearing around the assignment's position. */
  view: { distance: [number, number]; angle: [number, number] };
  overrides: Partial<Pick<Mission, 'subject' | 'technique' | 'contextSubjects' | 'viewpoint' | 'recommended' | 'lesson'>>;
}
export interface Mission {
  id: string; category: Category; title: string; description: string; lesson: string;
  technique: Technique; subject: string; location: string; ev: number;
  position: [number, number, number]; viewpoint: [number, number, number];
  timeWindow?: { start: number; end: number; preferred: number; label: string };
  requiredGear?: 'telephoto';
  contextSubjects?: string[];
  shots?: MissionShot[];
  reward: number; payment: number; recommended: { shutter: number; aperture: number; iso: number; filter: FilterId; tripod: boolean; panning: boolean; focalLength?: number };
}

const rec = (shutter: number, aperture: number, iso: number, filter: FilterId = 'none', tripod = false, panning = false) => ({ shutter, aperture, iso, filter, tripod, panning });
export const missions: Mission[] = [
  { id: 'nature-1', timeWindow: { start: 16.5, end: 18, preferred: 17, label: 'Golden hour · 16:30–18:00' }, category: 'Nature', title: 'Chasing the golden hour', description: 'The lake is quiet, the light is warm. Make a photograph of the little lighthouse that feels like the end of a perfect day.', lesson: 'Start with a balanced exposure. Stop down to f/8 or smaller for a landscape with more depth in focus.', technique: 'landscape', subject: 'Lighthouse', location: 'Willow Lake', ev: 12, position: [-7, 4, -17], viewpoint: [1, 1.7, 13], reward: 120, payment: 120, recommended: rec(1 / 60, 8, 100) },
  { id: 'nature-2', category: 'Nature', title: 'Let the water wander', description: 'Fern Creek tumbles over the mossy cliff, gathers in a plunge pool, and winds into Willow Lake. Turn its whitewater into a soft ribbon while keeping the rocks still.', lesson: 'Use a slow shutter, a tripod, and an ND filter. An ND filter cuts light so a long exposure does not wash out the scene.', technique: 'water', subject: 'Waterfall', location: 'Fern Creek', ev: 13, position: [-24, 4.3, -9.8], viewpoint: [-24, 1.7, 14], reward: 180, payment: 180, recommended: rec(0.5, 8, 100, 'nd6', true) },
  { id: 'sports-1', category: 'Sports', title: 'A fraction of a second', description: 'Catch the runner as they round the track. June at the local newspaper needs a sharp, energetic race photograph. Theo will show you the track.', lesson: 'Try 1/1000 s or faster. Raise ISO to keep the exposure balanced: a little noise is better than missing the moment.', technique: 'freeze', subject: 'Runner', location: 'Oakfield Track', ev: 11, position: [27, 1.4, 7], viewpoint: [22, 1.7, 19], reward: 160, payment: 160, recommended: rec(1 / 1000, 4, 800) },
  { id: 'sports-2', category: 'Sports', title: 'The world rushes by', description: 'Make a photograph that feels fast. Follow the runner with your camera while the track blurs behind them.', lesson: 'Use around 1/30–1/125 s and track the subject. The prototype Panning switch stands in for steady camera tracking.', technique: 'pan', subject: 'Runner', location: 'Oakfield Track', ev: 11, position: [27, 1.4, 7], viewpoint: [22, 1.7, 19], reward: 180, payment: 180, recommended: rec(1 / 60, 8, 200, 'none', false, true) },
  { id: 'news-1', timeWindow: { start: 6, end: 9, preferred: 7, label: 'Morning edition · 06:00–09:00' }, category: 'News', title: 'Through the glass', description: 'A baker is preparing the first loaves behind the shop window. Photograph the work through the reflections.', lesson: 'A circular polarizer can reduce some glass reflections at the right angle. It also absorbs light; compensate for that loss.', technique: 'glass', subject: 'Baker', location: 'Morning Paper Square', ev: 10, position: [13, 1.5, -14], viewpoint: [13, 1.7, -5], reward: 140, payment: 140, recommended: rec(1 / 60, 4, 200, 'cpl') },
  { id: 'news-2', timeWindow: { start: 18, end: 20, preferred: 19, label: 'Evening edition · 18:00–20:00' }, category: 'News', title: 'The evening edition', description: 'Photograph the reporter at the square before the evening paper goes to print. A usable moment comes first.', lesson: 'Keep a handheld shutter of at least 1/125 s. Use higher ISO when the light drops; news pictures can still work with noise.', technique: 'news', subject: 'Reporter', location: 'Morning Paper Square', ev: 8, position: [8, 1.4, -7], viewpoint: [8, 1.7, 1], reward: 160, payment: 160, recommended: rec(1 / 125, 4, 800) },
  { id: 'wedding-1', category: 'Wedding', title: 'Just the two of us', description: 'The newlyweds have a quiet moment beneath the garden arch. Give them a portrait with a gentle background.', lesson: 'A wide aperture such as f/2.8 helps separate your subjects from their surroundings. Keep both faces in the frame.', technique: 'couple', subject: 'Newlyweds', location: 'Rose Garden', ev: 11, position: [-43, 1.5, 29], viewpoint: [-43, 1.7, 39], reward: 150, payment: 150, recommended: rec(1 / 250, 2.8, 100) },
  { id: 'wedding-2', category: 'Wedding', title: 'Room for everyone', description: 'The family is ready for the group photograph. Make sure nobody disappears into a soft blur.', lesson: 'Stop down to f/8 or smaller for a group with more depth. Adjust shutter and ISO to compensate for the smaller aperture.', technique: 'group', subject: 'Wedding guests', location: 'Rose Garden', ev: 11, position: [-35, 1.4, 32.4], viewpoint: [-35, 1.7, 44], reward: 170, payment: 170, recommended: rec(1 / 125, 8, 400) },
  { id: 'studio-1', category: 'Studio', title: 'A little character', description: 'The pottery maker needs a portrait for their new collection. Move the key light to shape their face and use fill to soften the shadows.', lesson: 'Try f/2.8–f/5.6 and modest ISO. Open Lighting to move the key, fill, and rim lights, or try a close flash portrait against a darker room.', technique: 'portrait', subject: 'Pottery maker', location: 'Daylight Studio', ev: 9, position: [28, 1.5, -26], viewpoint: [28, 1.7, -16], reward: 140, payment: 140, recommended: rec(1 / 125, 2.8, 200) },
  { id: 'studio-2', category: 'Studio', title: 'Made by hand', description: 'Photograph the maker’s terracotta vase on the studio pedestal. Let the shape and small details tell the story.', lesson: 'A small aperture helps keep the product in focus. A tripod lets you use a longer shutter and low ISO for a clean file.', technique: 'product', subject: 'Terracotta vase', location: 'Daylight Studio', ev: 9, position: [32, 1.5, -26], viewpoint: [32, 1.7, -19], reward: 150, payment: 150, recommended: rec(1 / 8, 8, 100, 'none', true) },
  { id: 'astro-1', timeWindow: { start: 21, end: 4, preferred: 23, label: 'Dark sky · 21:00–04:00' }, category: 'Astro', title: 'A sky full of stories', description: 'Head to the dark-sky overlook and photograph the stars above the mountain. Give the sensor time to find the light.', lesson: 'Start with 10 seconds, f/2.8, ISO 1600, and a tripod. The shutter limit before stars trail depends on focal length.', technique: 'stars', subject: 'Night sky', location: 'Stargazer Ridge', ev: -4, position: [-53, 42, -100], viewpoint: [-53, 21.7, -70], reward: 200, payment: 200, recommended: rec(10, 2.8, 1600, 'none', true) },
  { id: 'astro-2', timeWindow: { start: 21, end: 4, preferred: 23, label: 'Dark sky · 21:00–04:00' }, category: 'Astro', title: 'Written in the sky', description: 'Stay a little longer. Make the stars draw paths through the night over the ridge.', lesson: 'Here, movement is the photograph: use 30 seconds or longer and a tripod. Real star-trail images often need minutes or stacked frames.', technique: 'trails', subject: 'Night sky', location: 'Stargazer Ridge', ev: -4, position: [-53, 42, -100], viewpoint: [-53, 21.7, -70], reward: 220, payment: 220, recommended: rec(30, 2.8, 800, 'none', true) },
];
missions.push({ id: 'nature-birds', category: 'Nature', title: 'A flash of blue', description: 'Find the kingfisher on its wetland perch. Make a close-up from the trail without disturbing the bird.', lesson: 'Equip the 200–600 mm lens, zoom to at least 400 mm, and use 1/1000 s or faster. Stay at least 18 m away; longer lenses also magnify camera shake.', technique: 'bird', requiredGear: 'telephoto', subject: 'Kingfisher', location: 'Kingfisher Wetland', ev: 12, position: [76, 3.6, -54], viewpoint: [63, 2.9, -32], reward: 240, payment: 260, recommended: { ...rec(1 / 1000, 5.6, 800), focalLength: 600 } });
missions.push({ id: 'intro-deer', category: 'Nature', title: 'A different kind of hunting', description: 'Walk inland from the arrival dock, then follow the western trail past the chapel. Mara lent you a camera. Find the deer in the western meadow and bring back a photograph, keeping at least six metres away.', lesson: 'C toggles a slow, quiet sneak. Approach carefully: walking close or running will startle the deer. Back away and let it settle before trying again. Drag to aim, E to raise the viewfinder, and Space to take a photograph. Your camera is already set for a quick first shot. Leave the deer undisturbed.', technique: 'wildlife', subject: 'Meadow deer', location: 'Western meadow', ev: 12, position: [-72, 6, 60], viewpoint: [-61, 1.7, 53], reward: 40, payment: 0, recommended: rec(1 / 500, 5.6, 400) });
export const categories: Category[] = ['Nature', 'Sports', 'News', 'Wedding', 'Studio', 'Astro'];
missions.push({ id: 'news-townhall', category: 'News', title: 'Behind closed doors', description: 'June has a tip: Councillor Vale is meeting a developer in the town hall after hours. From the public path, photograph Vale and the papers on the desk through the reflected window. June will investigate what the documents mean.', lesson: 'Wait until 22:00–02:00. Fit a CPL to reduce the window reflection, use a steady 1/125 s or faster, and raise ISO for the dim room. Keep the flash off.', technique: 'meeting', subject: 'Councillor Vale', location: 'Willowbrook Town Hall', ev: 5, position: [4, 1.5, -36], viewpoint: [4, 1.7, -25], timeWindow: { start: 22, end: 2, preferred: 23, label: 'After hours · 22:00–02:00' }, reward: 280, payment: 280, recommended: rec(1 / 125, 2.8, 6400, 'cpl') });
missions.push({ id: 'nature-bear', category: 'Nature', title: 'One last wild thing', description: 'Uncle Arthur remembers a rare pale bear in the northern woods. Mara has found its clearing. Bring home a photograph from the marked overlook, without approaching or disturbing it. You need the 200–600 mm wildlife lens before accepting this assignment.', lesson: 'Stay at least 20 m away. Equip the wildlife lens at 200–600 mm, use 1/500 s or faster and keep the flash off. The photograph is a gift, not a trophy.', technique: 'bear', requiredGear: 'telephoto', subject: 'Pale woodland bear', location: 'Northern bear clearing', ev: 12, position: [-88, 10, -91], viewpoint: [-66, 1.7, -77], reward: 320, payment: 0, recommended: { ...rec(1 / 500, 5.6, 400), focalLength: 250 } });

missions.push({ id: 'news-boundary', category: 'News', title: 'The line on the map', description: 'June has found a public proposal for a road through the northern woodland. Follow the ridge trail to the orange survey ribbons. Photograph the planning notice with the old footpath and trees around it, showing what the proposal would change. Then take both pictures to June in the square.', lesson: 'A useful documentary photograph includes context. Use the 35 mm lens and f/8 or smaller to keep the notice and its surroundings in focus. A photograph raises questions; June checks the public record before publishing.', technique: 'landscape', subject: 'Woodland survey notice', location: 'Northern footpath boundary', ev: 12, position: [-40, 5, -45], viewpoint: [-34, 1.7, -37], reward: 180, payment: 140, recommended: rec(1 / 125, 8, 200) });

for (const place of regionalLandmarks) missions.push({
  id: place.mission, category: 'Nature', title: ({ 'sea-light': 'The light that brought us home', observatory: 'A roof open to the sky', viaduct: 'What the valley kept', windmill: 'The hill where we waited' })[place.id],
  description: place.description, lesson: 'Arthur’s four horizons: make a landscape at f/8 or smaller. Keep the landmark and its surroundings in the frame. Print each photograph at the gallery, then visit Arthur to share the album.',
  technique: 'landscape', subject: place.name, location: place.name, ev: 12,
  position: [place.x, terrainHeight(place.x, place.z) + place.height * 0.47, place.z],
  viewpoint: [place.viewpoint[0], terrainHeight(place.viewpoint[0], place.viewpoint[1]) + 1.7, place.viewpoint[1]],
  reward: 140, payment: 100, recommended: rec(1 / 125, 8, 200),
});

missions.push({ id: 'harbor-portrait', category: 'News', title: 'The other end of the road', description: 'Ruth repairs the boats that bring Willowbrook home. She needs deliveries, but the proposed woodland road troubles her too. Meet her at Tidewright Workshop, then photograph her with the unfinished boat. Leave room for the work that explains why she is here.', lesson: 'An environmental portrait tells a story through a person and their surroundings. Use the 35 mm lens, f/8 or smaller and 1/125 s or faster. Include Ruth and the unfinished boat; a tight headshot leaves out half the story.', technique: 'environmental', subject: 'Ruth and her work', contextSubjects: ['Ruth the boatbuilder', 'Unfinished harbor boat'], location: 'Tidewright Workshop', ev: 12, position: [44.2, 2.3, 84.8], viewpoint: [45, 2.5, 75], reward: 160, payment: 120, recommended: rec(1 / 125, 8, 200) });
missions.push({ id: 'harbor-crew', category: 'News', title: 'Room for a different answer', description: 'After June’s report, Ruth and her apprentices sketch a delivery bay by the existing harbor lane. It is an idea for the hearing, not an approved plan. Photograph all three with the boat they are repairing. Print both workshop photographs and bring them to Ruth before she shares their story with June.', lesson: 'Keep Ruth, Nessa and Kit in the same frame, with the unfinished boat. Stop down to f/8 or smaller and use a steady 1/125 s or faster. Context matters as much as a clear face.', technique: 'environmental', subject: 'Harbor repair crew', contextSubjects: ['Ruth the boatbuilder', 'Nessa the apprentice', 'Kit the apprentice', 'Unfinished harbor boat'], location: 'Tidewright Workshop', ev: 12, position: [45, 2.3, 84], viewpoint: [45, 2.5, 74.8], reward: 180, payment: 160, recommended: rec(1 / 125, 8, 200) });

const ruthBrief = missions.find(m => m.id === 'harbor-portrait')!;
ruthBrief.description += ' Make a two-picture story: her place in the workshop, then a closer portrait from the west side of the yard. Ruth wants readers to see a person as well as an argument.';
ruthBrief.shots = [
  { id: 'place', title: 'A place to work', description: 'From the lane in front of the workshop, stand 8–18 m back. Include Ruth and the full unfinished boat at f/8 or smaller.', view: { distance: [8,18], angle: [0,15] }, overrides: {} },
  { id: 'person', title: 'The person behind the work', description: 'Move west and closer, 4–8 m from the middle of the yard and 25–75° around from the first view. Frame Ruth herself. Use f/2.8–f/5.6 to soften the background.', view: { distance: [4,8], angle: [25,75] }, overrides: { subject: 'Ruth the boatbuilder', technique: 'portrait', contextSubjects: undefined, viewpoint: [38.5,2.5,79.5], recommended: rec(1/250,4,100), lesson: 'Move your feet to change the angle. A closer portrait with a wider aperture makes Ruth the focus; the establishing frame already explains her work.' } },
];
const potteryBrief = missions.find(m => m.id === 'studio-2')!;
potteryBrief.description += ' Deliver two views: the whole vase on its pedestal and a closer oblique view that brings out the rim and curve.';
potteryBrief.shots = [
  { id: 'whole', title: 'The whole form', description: 'Start in front of the pedestal, 6–10 m back. Keep the vase and its setting clear with f/8, low ISO and a tripod.', view: { distance: [6,10], angle: [0,15] }, overrides: {} },
  { id: 'curve', title: 'Rim and curve', description: 'Pack the tripod and move to the right, 3–6 m away and 25–70° around the vase. Set the tripod again for a closer view of its form.', view: { distance: [3,6], angle: [25,70] }, overrides: { viewpoint: [33.8,1.7,-23.5], lesson: 'Changing position reveals a different side of the vase. Keep f/8 or smaller, ISO 100–200 and the tripod; zooming from the first position cannot replace this angle.' } },
];
